name: FestPlugin
main: com.festp.mainListener
autor: FEST_Channel
version: 1.2.0
commands:
         fest:
         enderchest:
         ec:
         boss:
         item:
         el:
api-version: 1.13